import { StudentProfile, FeeItem, ScheduleItem, Announcement } from '../types';

export const initialProfile: StudentProfile = {
  id: 'STU-2026-8842',
  name: 'Aisha Malik',
  email: 'aisha.malik@campusconnect.edu',
  phone: '+1 (555) 234-5678',
  rollNumber: 'BSCS-2026-042',
  department: 'Computer Science & AI',
  program: 'B.Sc. Computer Science',
  semester: 4,
  gpa: 3.82,
  attendancePct: 91.5,
  photoUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=400',
  dob: '2004-06-15',
  address: '45 University Ave, Tech District, Suite 302',
  guardianName: 'Tariq Malik',
  guardianPhone: '+1 (555) 876-5432',
  registrationStatus: 'Approved',
  registrationDate: '2026-01-12',
};

export const initialFeeItems: FeeItem[] = [
  {
    id: 'FEE-101',
    title: 'Spring 2026 Tuition Fee',
    category: 'Tuition',
    amount: 2400,
    dueDate: '2026-08-15',
    semester: 'Semester 4',
    status: 'Pending',
    invoiceNumber: 'INV-2026-001',
  },
  {
    id: 'FEE-102',
    title: 'AI & Data Science Lab Access',
    category: 'Lab',
    amount: 350,
    dueDate: '2026-08-15',
    semester: 'Semester 4',
    status: 'Pending',
    invoiceNumber: 'INV-2026-002',
  },
  {
    id: 'FEE-103',
    title: 'Digital Library & E-Resource Pass',
    category: 'Library',
    amount: 150,
    dueDate: '2026-02-10',
    semester: 'Semester 4',
    status: 'Paid',
    paidDate: '2026-02-08',
    transactionId: 'TXN-99381204',
    paymentMethod: 'Credit Card',
    invoiceNumber: 'INV-2026-003',
  },
  {
    id: 'FEE-104',
    title: 'Mid-Term Exam & Evaluation Fee',
    category: 'Exam',
    amount: 200,
    dueDate: '2026-03-01',
    semester: 'Semester 4',
    status: 'Paid',
    paidDate: '2026-02-28',
    transactionId: 'TXN-88219401',
    paymentMethod: 'UPI / Banking',
    invoiceNumber: 'INV-2026-004',
  },
  {
    id: 'FEE-105',
    title: 'Sports & Campus Recreation Facility',
    category: 'Facilities',
    amount: 100,
    dueDate: '2026-08-25',
    semester: 'Semester 4',
    status: 'Pending',
    invoiceNumber: 'INV-2026-005',
  },
];

export const initialSchedule: ScheduleItem[] = [
  {
    id: 'SCH-1',
    subject: 'Machine Learning & Neural Networks',
    code: 'CS-401',
    instructor: 'Dr. Robert Vance',
    room: 'Lab 3B (AI Tower)',
    day: 'Monday',
    time: '09:00 AM - 10:30 AM',
    duration: '1.5 hrs',
    type: 'Lecture',
    attendanceRate: 94,
    totalClasses: 18,
    attendedClasses: 17,
  },
  {
    id: 'SCH-2',
    subject: 'Database Systems Architecture',
    code: 'CS-308',
    instructor: 'Prof. Sarah Jenkins',
    room: 'Hall B (Science Block)',
    day: 'Monday',
    time: '11:00 AM - 12:30 PM',
    duration: '1.5 hrs',
    type: 'Lecture',
    attendanceRate: 88,
    totalClasses: 18,
    attendedClasses: 16,
  },
  {
    id: 'SCH-3',
    subject: 'Cloud Infrastructure & DevOps',
    code: 'CS-420',
    instructor: 'Eng. Marcus Thorne',
    room: 'Server Lab 2',
    day: 'Tuesday',
    time: '01:30 PM - 03:30 PM',
    duration: '2.0 hrs',
    type: 'Lab',
    attendanceRate: 100,
    totalClasses: 12,
    attendedClasses: 12,
  },
  {
    id: 'SCH-4',
    subject: 'Software Engineering Principles',
    code: 'CS-312',
    instructor: 'Dr. Elena Rostova',
    room: 'Auditorium 1',
    day: 'Wednesday',
    time: '10:00 AM - 11:30 AM',
    duration: '1.5 hrs',
    type: 'Lecture',
    attendanceRate: 85,
    totalClasses: 20,
    attendedClasses: 17,
  },
  {
    id: 'SCH-5',
    subject: 'Mobile Application Engineering',
    code: 'CS-415',
    instructor: 'Prof. David Chen',
    room: 'App Studio 4',
    day: 'Thursday',
    time: '09:00 AM - 11:00 AM',
    duration: '2.0 hrs',
    type: 'Lab',
    attendanceRate: 92,
    totalClasses: 14,
    attendedClasses: 13,
  },
  {
    id: 'SCH-6',
    subject: 'Ethics in Artificial Intelligence',
    code: 'HUM-201',
    instructor: 'Dr. Maya Lin',
    room: 'Seminar Room 12',
    day: 'Friday',
    time: '02:00 PM - 03:30 PM',
    duration: '1.5 hrs',
    type: 'Tutorial',
    attendanceRate: 90,
    totalClasses: 10,
    attendedClasses: 9,
  },
];

export const initialAnnouncements: Announcement[] = [
  {
    id: 'ANN-1',
    title: 'Spring 2026 Tuition Fee Payment Deadline Extended',
    content: 'The Registrar office has extended the tuition fee installment deadline to August 20, 2026. Late fees will be waived for students applying through CampusConnect AI installment plans.',
    category: 'Fee Alert',
    date: '2026-07-24',
    author: 'Office of the Bursar',
    isUrgent: true,
    pinned: true,
  },
  {
    id: 'ANN-2',
    title: 'Campus Hackathon 2026 & AI Project Expo Registration Open',
    content: 'Join the annual CampusConnect Hackathon on Sept 5-6! Win cash prizes up to $5,000 and direct interview vouchers with top tech partners. Submit your team proposal via the AI Assistant.',
    category: 'Event',
    date: '2026-07-22',
    author: 'Department of Computer Science',
    isUrgent: false,
    pinned: true,
  },
  {
    id: 'ANN-3',
    title: 'Mid-Semester Exam Timetable Published',
    content: 'The tentative schedule for Mid-Semester examinations is now available in your schedule section. Any clashes must be reported to the Controller of Examinations before August 10.',
    category: 'Exam',
    date: '2026-07-20',
    author: 'Examination Cell',
    isUrgent: false,
  },
  {
    id: 'ANN-4',
    title: 'Merit Scholarship Applications for Fall 2026',
    content: 'Students with GPA 3.5+ can now apply for up to 50% tuition waiver scholarships. Use the CampusConnect AI Scholarship Estimator tool to instantly assess your eligibility.',
    category: 'Academic',
    date: '2026-07-18',
    author: 'Student Financial Aid Committee',
    isUrgent: false,
  },
];

export const pendingRegistrations = [
  {
    id: 'REG-2026-091',
    fullName: 'Zayd Al-Hassan',
    email: 'zayd.alhassan@email.com',
    phone: '+1 (555) 432-8765',
    dob: '2005-03-22',
    gender: 'Male',
    department: 'Computer Science & AI',
    program: 'B.Sc. Data Science',
    previousGpa: '3.88',
    feePlan: 'Semester Full',
    status: 'Pending Review' as const,
    date: '2026-07-25',
    documentSummary: 'High School Diploma (A+ Grade), Transcript verified with 94.2% overall aggregate.',
  },
  {
    id: 'REG-2026-092',
    fullName: 'Sophia Martinez',
    email: 'sophia.m@email.com',
    phone: '+1 (555) 912-3456',
    dob: '2004-11-09',
    gender: 'Female',
    department: 'Business & Management',
    program: 'BBA Digital Marketing',
    previousGpa: '3.65',
    feePlan: 'Two Installments',
    status: 'Pending Review' as const,
    date: '2026-07-24',
    documentSummary: 'SAT Score 1380, High School Certificate uploaded.',
  },
];
